### ISSUE TITLE
Could you please use  rxjs instead of @reactivex/rxjs ?

### ISSUE THREAD

**Issue by kamalpatel125** [ngUpgraders/ng-forward#130] opened 2016-01-04 15:44 UTC
Hi, Somehow we can not get node modules for @reactivex/rxjs  but we can get from "rxjs". Is it ok to change please ?

Thanks

**Comment by MikeRyan52** [comment] 2016-01-04 15:49
Duplicate of  #122

**Closed by MikeRyan52** 2016-01-04 15:49 UTC
