### ISSUE TITLE
Add set of core [property] directives for visible, disabled, etc

### ISSUE THREAD

**Issue by MikeRyan52** [ngUpgraders/ng-forward#15] opened 2015-10-08 12:48 UTC
With property bindings, we should probably add a list of core directives for common element properties. I know there is a list somewhere of native properties supported in the Angular 2 codebase.

Covers scenarios like:

```html
<input type="text" [disabled]="myComponent.disabled">
```

**Comment by timkindberg** [comment] 2015-10-12 16:49
I think this is a duplicate of #5. Reopen if not.

**Comment by timkindberg** [comment] 2015-10-12 16:50
Or perhaps its for the element's properties that are in addition to ones from #5?

**Closed by timkindberg** 2015-10-12 16:49 UTC
